### ISSUE TITLE
Issue installing your forked version of screenshot-basic

### ISSUE THREAD

**Issue by arthur-rl** [jonassvensson4/mugshot#2]
```
C:\DevelopmentServer\cfx-server-data\resources\screenshot-basic\ui\src\main.ts
[tsl] ERROR in C:\DevelopmentServer\cfx-server-data\resources\screenshot-basic\ui\src\main.ts(95,23)

      TS2554: Expected 4 arguments, but got 2.
C:\DevelopmentServer\cfx-server-data\resources\screenshot-basic\ui\src\main.ts
[tsl] ERROR in C:\DevelopmentServer\cfx-server-data\resources\screenshot-basic\ui\src\main.ts(100,26)

      TS2554: Expected 1 arguments, but got 0.
C:\DevelopmentServer\cfx-server-data\resources\screenshot-basic\ui\src\main.ts
[tsl] ERROR in C:\DevelopmentServer\cfx-server-data\resources\screenshot-basic\ui\src\main.ts(102,18)

      TS2554: Expected 3 arguments, but got 2.
C:\DevelopmentServer\cfx-server-data\resources\screenshot-basic\ui\src\main.ts
[tsl] ERROR in C:\DevelopmentServer\cfx-server-data\resources\screenshot-basic\ui\src\main.ts(126,23)

      TS2554: Expected 4 arguments, but got 2.
Error: webpack got an error
```
When trying to start screenshot-basic

**Comment by jnsvns** [comment]
This is not an issue with just my forked version of that repo. Have you even had a look in the original repo? There are people with the same issue like yours, and there's a solution that's working for some people. https://github.com/citizenfx/screenshot-basic/issues/24

Please have a look in the original repo before opening a new issue next time.

**Comment by arthur-rl** [comment]
this only happens with your fork, when i use the normal version this does not happen.

**Comment by jnsvns** [comment]
Like I said, this is not an issue with my fork. It's the exact same problem as you can clearly see? You're probably using an older version of three.js for the original one.
