### ISSUE TITLE
Issue with encoding when doing mugshot

### ISSUE THREAD

**Issue by xYouLL** [jonassvensson4/mugshot#4]
Hello, I have an issue with encoding while not using imgur.
Everytime I do the mugshot it saves me the file as .undefined, it makes the screenshot but not the crop.
This is the cb of the requestScreenShotUpload cb func.
[image](https://i.imgur.com/m7A9vkY.png)

**Comment by jnsvns** [comment]
This resource doesn't encode anything. It's simply just displaying the mugshot of the ped for a couple of seconds and then screenshoting the game using the screenshot-basic resource.

I don't even know what service you're using so how could I possibly know why it's generating an undefined file? I think you'll be better off asking this question in the original screenshot-basic thread. Or debugging the service that you're using to see why it's returning an undefined file, it might be needing additional parameters in the body for example.

**Comment by xYouLL** [comment]
Not considering the screenshot-basic resource, the main problem is that the resource doesn't crop the image.
